### Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
#set -g @plugin 'dreamsofcode-io/catppuccin-tmux'
#set -g @plugin 'odedlaz/tmux-onedark-theme'
set -g @plugin 'vaaleyard/tmux-dotbar'
set -g @plugin 'joshmedeski/t-smart-tmux-session-manager'
set -g @t-fzf-prompt '  '

### Theme configs
#set -g @catppuccin_flavor 'mocha'
#set -g @catppuccin_window_status_style "rounded"

# Carrega tema
#run '#{TMUX_PLUGIN_MANAGER_PATH}/tmux/catppuccin.tmux'

set -g @tmux-dotbar-right true
set -g @tmux-dotbar-status-right-text " %H:%M "
set -g @tmux-dotbar-position top

# Barra de status
set -g allow-rename on
set -g status-position bottom
set -g status-interval 5
set -g status-left-length 100
set -g status-right-length 100
