# Caminho do TPM
set-environment -gF TMUX_PLUGIN_MANAGER_PATH '#{HOME}/.local/share/tmux/plugins/'

if 'test ! -d "${TMUX_PLUGIN_MANAGER_PATH}/tpm"' {
  run 'mkdir -p "${TMUX_PLUGIN_MANAGER_PATH}"'
  run 'git clone https://github.com/tmux-plugins/tpm "${TMUX_PLUGIN_MANAGER_PATH}/tpm"'
  run '${TMUX_PLUGIN_MANAGER_PATH}/tpm/bin/install_plugins'
}

# Carrega binds e tema
source-file ~/.config/tmux/binds.conf
source-file ~/.config/tmux/theme.conf

# Configuração geral
set -g mouse on
set -g prefix C-f
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
setw -g mode-keys vi
set-option -sa terminal-overrides ",xterm*:Tc"

# Prefix
set -g prefix C-f

# Inicializa o TPM
run '#{TMUX_PLUGIN_MANAGER_PATH}/tpm/tpm'
